### ISSUE TITLE
Missing Prefab

### ISSUE THREAD

**Issue by busiyg** [keijiro/4DViewsTest3#1]
I opened the project with 2020.1.2f and converted the textures with ffmpeg, but the sample4DViews_PresentingHOLOSYS_60fps_FILTERED prefab is missing in the scene. Where can I find it?
![image](https://user-images.githubusercontent.com/19410559/91125570-9fff8600-e6d4-11ea-9860-6be0d88e8253.png)

**Comment by keijiro** [comment]
Please check README.md ("The volumetric video data files are missing...").
